### ISSUE TITLE
Missing quotes with courier-mta v0.68.2

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/couriersrs#1]
@mawis This is the clone of your website (with CAcert certificate that is not in modern browsers by default).
Is it possible that you update Couriersrs to be compatible with latest courier-mta?

**Comment by szepeviktor** [comment]
With courier-mta v0.65.0 the new recipient is 

```
<".xalias/info@origdomain+2ehu"@domain.net>
```

with v0.68.2 it is 

```
<.xalias/proba@origdomain+2ehu@domain.hu>
```

without `"`-s thus - I think - it is an invalid address.

```
courieresmtpd: error,relay=::ffff:95.140.33.67,from=<viktor@szepe.net>,
to=<proba@origdomain.hu>: 550 User <.xalias/proba@origdomain+2ehu@domain.hu> unknown
```

libsrs version is the same in both cases: 1.0.18.

**Comment by szepeviktor** [comment]
No.

```
courierd: id=0000000000040B0E.000000005615AA28.000030CC,from=<root@domain.hu>,
addr=<".xalias/proba@origdomain+2ehu"@domain.hu>: 550 User <.xalias/proba@origdomain+2ehu@domain.hu> unknown
```

is also a failure with quotes.

**Comment by szepeviktor** [comment]
It turned out the the real cause is that the default domain is not being in locals.
http://markmail.org/thread/x3yhrrtw43cdxwty

**Comment by szepeviktor** [comment]
@mawis Excuse me for the false alarm.

**Comment by mawis** [comment]
Hi Viktor,

just to make sure: everything is fine now for you? Or is there still an
issue for you with couriersrs in your setup?

Regards,
Matthias

El 2015-10-07 17:01:20, Viktor Szépe escribió:

> Date: Wed, 07 Oct 2015 17:01:20 -0700
> From: Viktor Szépe notifications@github.com
> Subject: Re: [couriersrs] Missing quotes with courier-mta v0.68.2 (#1)
> To: szepeviktor/couriersrs couriersrs@noreply.github.com
> Cc: Matthias Wimmer m@tthias.eu
> Authentication-Results: hase.amessage.eu;  spf=pass
>  smtp.mailfrom=github.com;  dkim=neutral (test key, signature verification
>  failed) header.i=@github.com
> X-Bogosity: Ham, tests=bogofilter, spamicity=0.000000, version=1.2.4
> 
> @mawis Excuse me for the false alarm.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/szepeviktor/couriersrs/issues/1#issuecomment-146370986

## 

Matthias Wimmer
Contact details:     http://matthias.wimmer.tel/

**Comment by szepeviktor** [comment]
Thank you for your response.
It is OK now, the default domain being a virtual domain in Courier caused the above error.
